name: Go CI

on:
  workflow_dispatch:
  pull_request:
    branches: 
    - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Setup the environment
        run: make setup

      - name: Run fmt
        run: make fmt

      - name: Run vet
        run: make vet

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test
